spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rankhub-database.cxeecquwuy0s.ap-northeast-2.rds.amazonaws.com:3306/rankhub_db?serverTimezone=Asia/Seoul
    username: admin
    password: rankhubpw

  jpa:
    hibernate:
      ddl-auto: update   # 엔티티 기반으로 스키마 자동 반영
    properties:
      hibernate:
        show_sql: true   # 실행된 SQL 콘솔 출력
        format_sql: true # SQL 보기 좋게 포맷
    database-platform: org.hibernate.dialect.MySQLDialect